BASE_DIR = .
BIN_DIR = ./
INCLUDE_DIR = $(BASE_DIR)/include
DEPPARSER_DIR = $(BASE_DIR)/src/depparser

# set LD_LIBRARY_PATH
export CC  = gcc
export CXX = g++
export NVCC =nvcc
include $(BASE_DIR)/make/config.mk
include $(BASE_DIR)/make/mshadow.mk
export CFLAGS = -Wall -O3 -I$(INCLUDE_DIR)/ -fopenmp $(MSHADOW_CFLAGS)
export LDFLAGS= -lm $(MSHADOW_LDFLAGS)
export NVCCFLAGS = -O3 --use_fast_math -ccbin $(CXX) $(MSHADOW_NVCCFLAGS)

# specify tensor path
BIN = 
OBJ = $(DEPPARSER_DIR)/Config.o 
CUOBJ = $(DEPPARSER_DIR)/Depparser.o  
CUBIN = $(BASE_DIR)/bin/parser
.PHONY: clean all

all: $(BIN) $(OBJ) $(CUBIN) $(CUOBJ)

$(BASE_DIR)/bin/parser : $(DEPPARSER_DIR)/Depparser.cu

$(BIN) :
	$(CXX) $(CFLAGS) -o $@ $(filter %.cpp %.o %.c, $^)  $(LDFLAGS)

$(OBJ) :
	$(CXX) -c $(CFLAGS) $(firstword $(filter $(DEPPARSER_DIR)/%.cpp $(DEPPARSER_DIR)/%.c, $^) ) -o $@ 

$(CUOBJ) :
	$(NVCC) -c -o $@ $(NVCCFLAGS) -Xcompiler "$(CFLAGS)" $(filter %.cu, $^)

$(CUBIN) :
	$(NVCC) -o $@ $(NVCCFLAGS) -Xcompiler "$(CFLAGS)" -Xlinker "$(LDFLAGS)" $(filter %.cu %.cpp %.o, $^)

clean:
	$(RM) $(OBJ) $(BIN) $(CUBIN) $(CUOBJ) *~

